-- consultar tablespaces
SELECT TABLESPACE_NAME, FILE_NAME, BYTES /1024/1024 AS SIZE_MB
FROM DBA_DATA_FILES;

-- crear tablespace
CREATE TABLESPACE FIDE_ARATIENDA_TBS
DATAFILE  'C:\APP\ALOPE\PRODUCT\21C\ORADATA\XE\ARATIENDA.DBF' SIZE 100M

-- mover las tablas creadas al tablespace
ALTER TABLE FIDE_ARATIENDA.FIDE_ROLES_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_USUARIOS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_PAIS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_PROVINCIA_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_CANTON_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_DISTRITO_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_DIRECCION_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_ESTADOS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_MONEDA_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_FORMA_PAGO_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_CLIENTES_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_EMPLEADOS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_PRODUCTOS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_INVENTARIO_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_TIENDAS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_PRODUCTO_TIENDA_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_CAJAS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_FACTURAS_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_DETALLE_FACTURA_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;
ALTER TABLE FIDE_ARATIENDA.FIDE_NOTAS_CREDITO_TB MOVE TABLESPACE FIDE_ARATIENDA_TBS;

-- verificar que se agregaron al tablespace
SELECT TABLE_NAME, OWNER, TABLESPACE_NAME
FROM DBA_TABLES
WHERE TABLESPACE_NAME = 'FIDE_ARATIENDA_TBS';




