
--insert de pais
INSERT INTO FIDE_PAIS_TB (ID_PAIS, NOMBRE_PAIS) VALUES (506, 'Costa Rica');
COMMIT;

--insert roles

INSERT INTO FIDE_ARATIENDA.FIDE_ROLES_TB (ID_ROL, NOMBRE_ROL, DESCRIPCION) VALUES (1, 'ADMINISTRADOR', 'ACCESO TOTAL AL SISTEMA');
INSERT INTO FIDE_ARATIENDA.FIDE_ROLES_TB (ID_ROL, NOMBRE_ROL, DESCRIPCION) VALUES (2, 'VENDEDOR', 'GESTIÓN DE PRODUCTOS Y FACTURAS');
INSERT INTO FIDE_ARATIENDA.FIDE_ROLES_TB (ID_ROL, NOMBRE_ROL, DESCRIPCION) VALUES (3, 'CLIENTE', 'CONSULTA DE ÓRDENES Y FACTURAS');
COMMIT;

--PROVINCIAS
INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (1, 'San José');
INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (2, 'Alajuela');
INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (3, 'Cartago');
INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (4, 'Heredia');
INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (5, 'Guanacaste');
INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (6, 'Puntarenas');
INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA) VALUES (7, 'Limón');
COMMIT;

--cantones de sj
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (101, 'San José', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (102, 'Escazú', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (103, 'Desamparados', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (104, 'Puriscal', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (105, 'Tarrazú', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (106, 'Aserrí', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (107, 'Mora', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (108, 'Goicoechea', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (109, 'Santa Ana', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (110, 'Alajuelita', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (111, 'Vásquez de Coronado', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (112, 'Acosta', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (113, 'Tibás', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (114, 'Moravia', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (115, 'Montes de Oca', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (116, 'Turrubares', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (117, 'Dota', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (118, 'Curridabat', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (119, 'Pérez Zeledón', 1);
INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_PROVINCIA) VALUES (120, 'León Cortés Castro', 1);

-- Provincia de Alajuela
INSERT INTO FIDE_CANTON_TB VALUES (201, 'Alajuela', 2);
INSERT INTO FIDE_CANTON_TB VALUES (202, 'San Ramón', 2);
INSERT INTO FIDE_CANTON_TB VALUES (203, 'Grecia', 2);
INSERT INTO FIDE_CANTON_TB VALUES (204, 'San Mateo', 2);
INSERT INTO FIDE_CANTON_TB VALUES (205, 'Atenas', 2);
INSERT INTO FIDE_CANTON_TB VALUES (206, 'Naranjo', 2);
INSERT INTO FIDE_CANTON_TB VALUES (207, 'Palmares', 2);
INSERT INTO FIDE_CANTON_TB VALUES (208, 'Poás', 2);
INSERT INTO FIDE_CANTON_TB VALUES (209, 'Orotina', 2);
INSERT INTO FIDE_CANTON_TB VALUES (210, 'San Carlos', 2);
INSERT INTO FIDE_CANTON_TB VALUES (211, 'Zarcero', 2);
INSERT INTO FIDE_CANTON_TB VALUES (212, 'Sarchí', 2);
INSERT INTO FIDE_CANTON_TB VALUES (213, 'Upala', 2);
INSERT INTO FIDE_CANTON_TB VALUES (214, 'Los Chiles', 2);
INSERT INTO FIDE_CANTON_TB VALUES (215, 'Guatuso', 2);
INSERT INTO FIDE_CANTON_TB VALUES (216, 'Río Cuarto', 2);

--cartago
INSERT INTO FIDE_CANTON_TB VALUES (301, 'Cartago', 3);
INSERT INTO FIDE_CANTON_TB VALUES (302, 'Paraíso', 3);
INSERT INTO FIDE_CANTON_TB VALUES (303, 'La Unión', 3);
INSERT INTO FIDE_CANTON_TB VALUES (304, 'Jiménez', 3);
INSERT INTO FIDE_CANTON_TB VALUES (305, 'Turrialba', 3);
INSERT INTO FIDE_CANTON_TB VALUES (306, 'Alvarado', 3);
INSERT INTO FIDE_CANTON_TB VALUES (307, 'Oreamuno', 3);
INSERT INTO FIDE_CANTON_TB VALUES (308, 'El Guarco', 3);

-- heredia
INSERT INTO FIDE_CANTON_TB VALUES (401, 'Heredia', 4);
INSERT INTO FIDE_CANTON_TB VALUES (402, 'Barva', 4);
INSERT INTO FIDE_CANTON_TB VALUES (403, 'Santo Domingo', 4);
INSERT INTO FIDE_CANTON_TB VALUES (404, 'Santa Bárbara', 4);
INSERT INTO FIDE_CANTON_TB VALUES (405, 'San Rafael', 4);
INSERT INTO FIDE_CANTON_TB VALUES (406, 'San Isidro', 4);
INSERT INTO FIDE_CANTON_TB VALUES (407, 'Belén', 4);
INSERT INTO FIDE_CANTON_TB VALUES (408, 'Flores', 4);
INSERT INTO FIDE_CANTON_TB VALUES (409, 'San Pablo', 4);

--guanacaste
INSERT INTO FIDE_CANTON_TB VALUES (501, 'Liberia', 5);
INSERT INTO FIDE_CANTON_TB VALUES (502, 'Nicoya', 5);
INSERT INTO FIDE_CANTON_TB VALUES (503, 'Santa Cruz', 5);
INSERT INTO FIDE_CANTON_TB VALUES (504, 'Bagaces', 5);
INSERT INTO FIDE_CANTON_TB VALUES (505, 'Carrillo', 5);
INSERT INTO FIDE_CANTON_TB VALUES (506, 'Cañas', 5);
INSERT INTO FIDE_CANTON_TB VALUES (507, 'Abangares', 5);
INSERT INTO FIDE_CANTON_TB VALUES (508, 'Tilarán', 5);
INSERT INTO FIDE_CANTON_TB VALUES (509, 'Nandayure', 5);
INSERT INTO FIDE_CANTON_TB VALUES (510, 'La Cruz', 5);
INSERT INTO FIDE_CANTON_TB VALUES (511, 'Hojancha', 5);

--puntarenas
INSERT INTO FIDE_CANTON_TB VALUES (601, 'Puntarenas', 6);
INSERT INTO FIDE_CANTON_TB VALUES (602, 'Esparza', 6);
INSERT INTO FIDE_CANTON_TB VALUES (603, 'Buenos Aires', 6);
INSERT INTO FIDE_CANTON_TB VALUES (604, 'Montes de Oro', 6);
INSERT INTO FIDE_CANTON_TB VALUES (605, 'Osa', 6);
INSERT INTO FIDE_CANTON_TB VALUES (606, 'Quepos', 6);
INSERT INTO FIDE_CANTON_TB VALUES (607, 'Golfito', 6);
INSERT INTO FIDE_CANTON_TB VALUES (608, 'Coto Brus', 6);
INSERT INTO FIDE_CANTON_TB VALUES (609, 'Parrita', 6);
INSERT INTO FIDE_CANTON_TB VALUES (610, 'Corredores', 6);
INSERT INTO FIDE_CANTON_TB VALUES (611, 'Garabito', 6);

--limon
INSERT INTO FIDE_CANTON_TB VALUES (701, 'Limón', 7);
INSERT INTO FIDE_CANTON_TB VALUES (702, 'Pococí', 7);
INSERT INTO FIDE_CANTON_TB VALUES (703, 'Siquirres', 7);
INSERT INTO FIDE_CANTON_TB VALUES (704, 'Talamanca', 7);
INSERT INTO FIDE_CANTON_TB VALUES (705, 'Matina', 7);
INSERT INTO FIDE_CANTON_TB VALUES (706, 'Guácimo', 7);
commit;


--DISTRITOS DE SJ

-- Cantón 101
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10101, 'Carmen', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10102, 'Merced', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10103, 'Hospital', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10104, 'Catedral', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10105, 'Zapote', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10106, 'San Francisco de Dos Ríos', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10107, 'Uruca', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10108, 'Mata Redonda', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10109, 'Pavas', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10110, 'Hatillo', 101);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10111, 'San Sebastián', 101);
-- Cantón 102
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10201, 'Escazú', 102);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10202, 'San Antonio', 102);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10203, 'San Rafael', 102);
-- Cantón 103
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10301, 'Desamparados', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10302, 'San Miguel', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10303, 'San Juan de Dios', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10304, 'San Rafael Arriba', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10305, 'San Antonio', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10306, 'Frailes', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10307, 'Patarrá', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10308, 'San Cristóbal', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10309, 'Rosario', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10310, 'Damas', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10311, 'San Rafael Abajo', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10312, 'Gravilias', 103);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10313, 'Los Guido', 103);
-- Cantón 104
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10401, 'Santiago', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10402, 'Mercedes Sur', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10403, 'Barbacoas', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10404, 'Grifo Alto', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10405, 'San Rafael', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10406, 'Candelarita', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10407, 'Desamparaditos', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10408, 'San Antonio', 104);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10409, 'Chires', 104);
-- Cantón 105
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10501, 'San Marcos', 105);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10502, 'San Lorenzo', 105);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10503, 'San Carlos', 105);
-- Cantón 106
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10601, 'Aserrí', 106);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10602, 'Tarbaca', 106);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10603, 'Vuelta de Jorco', 106);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10604, 'San Gabriel', 106);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10605, 'Legua', 106);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10606, 'Monterrey', 106);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10607, 'Salitrillos', 106);
-- Cantón 107
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10701, 'Colón', 107);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10702, 'Guayabo', 107);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10703, 'Tabarcia', 107);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10704, 'Piedras Negras', 107);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10705, 'Picagres', 107);
-- Cantón 108
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10801, 'Guadalupe', 108);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10802, 'San Francisco', 108);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10803, 'Calle Blancos', 108);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10804, 'Mata de Plátano', 108);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10805, 'Ipís', 108);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10806, 'Rancho Redondo', 108);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10807, 'Purral', 108);
-- Cantón 109
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10901, 'Santa Ana', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10902, 'Salitral', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10903, 'Pozos', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10904, 'Uruca', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10905, 'Piedades', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10906, 'Brasil', 109);
-- Cantón 110
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11001, 'Alajuelita', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11002, 'San Josecito', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11003, 'San Antonio', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11004, 'Concepción', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11005, 'San Felipe', 110);
-- Cantón 111
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11101, 'San Isidro', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11102, 'San Rafael', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11103, 'Dulce Nombre de Jesús', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11104, 'Patalillo', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11105, 'Cascajal', 111);
-- Cantón 112
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11201, 'San Ignacio', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11202, 'Guaitil', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11203, 'Palmichal', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11204, 'Cangrejal', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11205, 'Sabanillas', 112);
-- Cantón 113
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11301, 'San Juan', 113);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11302, 'Cinco Esquinas', 113);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11303, 'Anselmo Llorente', 113);
-- Cantón 114
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11401, 'San Vicente', 114);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11402, 'San Jerónimo', 114);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11403, 'La Trinidad', 114);
-- Cantón 115
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11501, 'San Pedro', 115);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11502, 'Sabanilla', 115);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11503, 'Mercedes', 115);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11504, 'San Rafael', 115);
-- Cantón 116
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11601, 'San Pablo', 116);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11602, 'San Pedro', 116);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11603, 'San Juan de Mata', 116);
-- Cantón 117
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11701, 'Santa María', 117);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11702, 'Jardín', 117);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11703, 'Copey', 117);
-- Cantón 118
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11801, 'Curridabat', 118);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11802, 'Granadilla', 118);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11803, 'Sánchez', 118);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11804, 'Tirrases', 118);
-- Cantón 119
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11901, 'San Isidro de El General', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11902, 'El General', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11903, 'Daniel Flores', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11904, 'Rivas', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11905, 'San Pedro', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11906, 'Platanares', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11907, 'Pejibaye', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11908, 'Cajón', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11909, 'Barú', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11910, 'Río Nuevo', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11911, 'Páramo', 119);
-- Cantón 120
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12001, 'San Pablo', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12002, 'San Andrés', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12003, 'Llano Bonito', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12004, 'San Isidro', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12005, 'Santa Cruz', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12006, 'San Antonio', 120);
-- Cantón 109
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10901, 'Santa Ana', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10902, 'Salitral', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10903, 'Pozos', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10904, 'Uruca', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10905, 'Piedades', 109);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (10906, 'Brasil', 109);
-- Cantón 110
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11001, 'Alajuelita', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11002, 'San Josecito', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11003, 'San Antonio', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11004, 'Concepción', 110);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11005, 'San Felipe', 110);
-- Cantón 111
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11101, 'San Isidro', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11102, 'San Rafael', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11103, 'Dulce Nombre de Jesús', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11104, 'Patalillo', 111);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11105, 'Cascajal', 111);
-- Cantón 112
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11201, 'San Ignacio', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11202, 'Guaitil', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11203, 'Palmichal', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11204, 'Cangrejal', 112);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11205, 'Sabanillas', 112);
-- Cantón 113
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11301, 'San Juan', 113);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11302, 'Cinco Esquinas', 113);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11303, 'Anselmo Llorente', 113);
-- Cantón 114
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11401, 'San Vicente', 114);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11402, 'San Jerónimo', 114);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11403, 'La Trinidad', 114);
-- Cantón 115
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11501, 'San Pedro', 115);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11502, 'Sabanilla', 115);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11503, 'Mercedes', 115);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11504, 'San Rafael', 115);
-- Cantón 116
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11601, 'San Pablo', 116);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11602, 'San Pedro', 116);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11603, 'San Juan de Mata', 116);
-- Cantón 117
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11701, 'Santa María', 117);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11702, 'Jardín', 117);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11703, 'Copey', 117);
-- Cantón 118
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11801, 'Curridabat', 118);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11802, 'Granadilla', 118);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11803, 'Sánchez', 118);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11804, 'Tirrases', 118);
-- Cantón 119
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11901, 'San Isidro de El General', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11902, 'El General', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11903, 'Daniel Flores', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11904, 'Rivas', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11905, 'San Pedro', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11906, 'Platanares', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11907, 'Pejibaye', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11908, 'Cajón', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11909, 'Barú', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11910, 'Río Nuevo', 119);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (11911, 'Páramo', 119);
-- Cantón 120
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12001, 'San Pablo', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12002, 'San Andrés', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12003, 'Llano Bonito', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12004, 'San Isidro', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12005, 'Santa Cruz', 120);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (12006, 'San Antonio', 120);

--DISTRITOS DE ALAJUELA

-- Cantón 201
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20101, 'Alajuela', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20102, 'San José', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20103, 'Carrizal', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20104, 'San Antonio', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20105, 'Guácima', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20106, 'San Isidro', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20107, 'Sabanilla', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20108, 'San Rafael', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20109, 'Río Segundo', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20110, 'Desamparados', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20111, 'Turrúcares', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20112, 'Tambor', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20113, 'Garita', 201);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20114, 'Sarapiquí', 201);
-- Cantón 202
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20201, 'San Ramón', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20202, 'Santiago', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20203, 'San Juan', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20204, 'Piedades Norte', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20205, 'Piedades Sur', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20206, 'San Rafael', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20207, 'San Isidro', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20208, 'Ángeles', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20209, 'Alfaro', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20210, 'Volio', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20211, 'Concepción', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20212, 'Zapotal', 202);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20213, 'Peñas Blancas', 202);
-- Cantón 203
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20301, 'Grecia', 203);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20302, 'San Isidro', 203);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20303, 'San José', 203);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20304, 'San Roque', 203);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20305, 'Tacares', 203);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20306, 'Río Cuarto', 203);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20307, 'Puente de Piedra', 203);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20308, 'Bolívar', 203);
-- Cantón 204
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20401, 'San Mateo', 204);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20402, 'Desmonte', 204);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20403, 'Jesús María', 204);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20404, 'Labrador', 204);
-- Cantón 205
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20501, 'Atenas', 205);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20502, 'Jesús', 205);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20503, 'Mercedes', 205);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20504, 'San Isidro', 205);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20505, 'Concepción', 205);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20506, 'San José', 205);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20507, 'Santa Eulalia', 205);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20508, 'Escobal', 205);
-- Cantón 206
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20601, 'Naranjo', 206);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20602, 'San Miguel', 206);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20603, 'San José', 206);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20604, 'Cirrí Sur', 206);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20605, 'San Jerónimo', 206);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20606, 'San Juan', 206);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20607, 'El Rosario', 206);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20608, 'Palmitos', 206);
-- Cantón 207
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20701, 'Palmares', 207);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20702, 'Zaragoza', 207);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20703, 'Buenos Aires', 207);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20704, 'Santiago', 207);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20705, 'Candelaria', 207);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20706, 'Esquipulas', 207);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20707, 'La Granja', 207);
-- Cantón 208
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20801, 'San Pedro', 208);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20802, 'San Juan', 208);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20803, 'San Rafael', 208);
-- Cantón 209
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20901, 'Orotina', 209);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20902, 'El Mastate', 209);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20903, 'Hacienda Vieja', 209);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20904, 'Coyolar', 209);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (20905, 'La Ceiba', 209);
-- Cantón 210
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21001, 'Quesada', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21002, 'Florencia', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21003, 'Buenavista', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21004, 'Aguas Zarcas', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21005, 'Venecia', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21006, 'Pital', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21007, 'La Fortuna', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21008, 'La Tigra', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21009, 'La Palmera', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21010, 'Venado', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21011, 'Cutris', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21012, 'Monterrey', 210);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21013, 'Pocosol', 210);
-- Cantón 211
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21101, 'Zarcero', 211);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21102, 'Laguna', 211);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21103, 'Tapezco', 211);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21104, 'Guadalupe', 211);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21105, 'Palmira', 211);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21106, 'Zapote', 211);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21107, 'Brisas', 211);
-- Cantón 212
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21201, 'Sarchí Norte', 212);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21202, 'Sarchí Sur', 212);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21203, 'Toro Amarillo', 212);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21204, 'San Pedro', 212);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21205, 'Rodríguez', 212);
-- Cantón 213
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21301, 'Upala', 213);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21302, 'Aguas Claras', 213);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21303, 'San José (Upala)', 213);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21304, 'Bijagua', 213);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21305, 'Delicias', 213);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21306, 'Dos Ríos', 213);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21307, 'Yolillal', 213);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21308, 'Canalete', 213);
-- Cantón 214
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21401, 'Los Chiles', 214);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21402, 'Caño Negro', 214);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21403, 'El Amparo', 214);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21404, 'San Jorge', 214);
-- Cantón 215
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21501, 'San Rafael', 215);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21502, 'Buenavista', 215);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21503, 'Cote', 215);
-- Cantón 216
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21601, 'Río Cuarto', 216);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21602, 'Santa Rita', 216);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (21603, 'Santa Isabel', 216);

--DISTRITOS DE CARTAGO

-- Cantón 301
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30101, 'Oriental', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30102, 'Occidental', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30103, 'Carmen', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30104, 'San Nicolás', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30105, 'Aguacaliente (San Francisco)', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30106, 'Guadalupe', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30107, 'Corralillo', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30108, 'Tierra Blanca', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30109, 'Dulce Nombre', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30110, 'Llano Grande', 301);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30111, 'Quebradilla', 301);
-- Cantón 302
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30201, 'Paraíso', 302);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30202, 'Santiago', 302);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30203, 'Orosi', 302);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30204, 'Cachí', 302);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30205, 'Llanos de Santa Lucía', 302);
-- Cantón 303
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30301, 'Tres Ríos', 303);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30302, 'San Diego', 303);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30303, 'San Juan', 303);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30304, 'San Rafael', 303);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30305, 'Concepción', 303);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30306, 'Dulce Nombre', 303);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30307, 'San Ramón', 303);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30308, 'Río Azul', 303);
-- Cantón 304
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30401, 'Juan Viñas', 304);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30402, 'Tucurrique', 304);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30403, 'Pejibaye', 304);
-- Cantón 305
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30501, 'Turrialba', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30502, 'La Suiza', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30503, 'Peralta', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30504, 'Santa Cruz', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30505, 'Santa Rosa', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30506, 'Pavones', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30507, 'Tuis', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30508, 'Tayutic', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30509, 'Santa Teresita', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30510, 'La Isabel', 305);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30511, 'Chirripó', 305);
-- Cantón 306
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30601, 'Pacayas', 306);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30602, 'Cervantes', 306);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30603, 'Capellades', 306);
-- Cantón 307
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30701, 'San Rafael', 307);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30702, 'Cot', 307);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30703, 'Potrero Cerrado', 307);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30704, 'Cipreses', 307);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30705, 'Santa Rosa', 307);
-- Cantón 308
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30801, 'El Tejar', 308);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30802, 'San Isidro', 308);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30803, 'Tobosi', 308);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (30804, 'Patio de Agua', 308);

--DISTRITOS DE HEREDIA

-- Cantón 401
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40101, 'Heredia', 401);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40102, 'Mercedes', 401);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40103, 'San Francisco', 401);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40104, 'Ulloa', 401);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40105, 'Vara Blanca', 401);
-- Cantón 402
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40201, 'Barva', 402);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40202, 'San Pedro', 402);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40203, 'San Pablo', 402);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40204, 'San Roque', 402);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40205, 'Santa Lucía', 402);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40206, 'San José de la Montaña', 402);
-- Cantón 403
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40301, 'Santo Domingo', 403);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40302, 'San Vicente', 403);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40303, 'San Miguel', 403);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40304, 'Paracito', 403);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40305, 'Santo Tomás', 403);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40306, 'Santa Rosa', 403);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40307, 'Tures', 403);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40308, 'Pará', 403);
-- Cantón 404
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40401, 'Santa Bárbara', 404);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40402, 'San Pedro', 404);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40403, 'San Juan', 404);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40404, 'Jesús', 404);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40405, 'Santo Domingo', 404);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40406, 'Purabá', 404);
-- Cantón 405
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40501, 'San Rafael', 405);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40502, 'San Josecito', 405);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40503, 'Santiago', 405);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40504, 'Ángeles', 405);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40505, 'Concepción', 405);
-- Cantón 406
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40601, 'San Isidro', 406);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40602, 'San José', 406);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40603, 'Concepción', 406);
-- Cantón 407
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40701, 'San Antonio', 407);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40702, 'La Ribera', 407);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40703, 'La Asunción', 407);
-- Cantón 408
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40801, 'San Joaquín', 408);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40802, 'Barrantes', 408);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40803, 'Llorente', 408);
-- Cantón 409
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40901, 'San Pablo', 409);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (40902, 'Rincón de Sabanilla', 409);

--DISTRITOS DE GUANACASTE

-- Cantón 501
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50101, 'Liberia', 501);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50102, 'Cañas Dulces', 501);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50103, 'Mayorga', 501);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50104, 'Nacascolo', 501);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50105, 'Curubandé', 501);
-- Cantón 502
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50201, 'Nicoya', 502);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50202, 'Mansión', 502);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50203, 'San Antonio', 502);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50204, 'Quebrada Honda', 502);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50205, 'Sámara', 502);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50206, 'Nosara', 502);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50207, 'Belén de Nosarita', 502);
-- Cantón 503
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50301, 'Santa Cruz', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50302, 'Bolsón', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50303, 'Veintisiete de Abril', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50304, 'Tempate', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50305, 'Cartagena', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50306, 'Cuajiniquil', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50307, 'Diriá', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50308, 'Cabo Velas', 503);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50309, 'Tamarindo', 503);
-- Cantón 504
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50401, 'Bagaces', 504);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50402, 'La Fortuna', 504);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50403, 'Mogote', 504);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50404, 'Río Naranjo', 504);
-- Cantón 505
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50501, 'Filadelfia', 505);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50502, 'Palmira', 505);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50503, 'Sardinal', 505);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50504, 'Belén', 505);
-- Cantón 506
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50601, 'Cañas', 506);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50602, 'Palmira', 506);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50603, 'San Miguel', 506);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50604, 'Bebedero', 506);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50605, 'Porozal', 506);
-- Cantón 507
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50701, 'Las Juntas', 507);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50702, 'Sierra', 507);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50703, 'San Juan', 507);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50704, 'Colorado', 507);
-- Cantón 508
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50801, 'Tilarán', 508);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50802, 'Quebrada Grande', 508);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50803, 'Tronadora', 508);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50804, 'Santa Rosa', 508);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50805, 'Líbano', 508);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50806, 'Tierras Morenas', 508);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50807, 'Arenal', 508);
-- Cantón 509
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50901, 'Carmona', 509);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50902, 'Santa Rita', 509);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50903, 'Zapotal', 509);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50904, 'San Pablo', 509);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50905, 'Porvenir', 509);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (50906, 'Bejuco', 509);
-- Cantón 510
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51001, 'La Cruz', 510);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51002, 'Santa Cecilia', 510);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51003, 'La Garita', 510);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51004, 'Santa Elena', 510);
-- Cantón 511
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51101, 'Hojancha', 511);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51102, 'Monte Romo', 511);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51103, 'Puerto Carrillo', 511);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51104, 'Huacas', 511);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (51105, 'Matambú', 511);

--DISTRITOS DE PUNTARENAS

-- Cantón 601
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60101, 'Puntarenas', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60102, 'Pitahaya', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60103, 'Chomes', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60104, 'Lepanto', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60105, 'Paquera', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60106, 'Manzanillo', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60107, 'Guacimal', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60108, 'Barranca', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60109, 'Monte Verde', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60110, 'Isla del Coco', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60111, 'Cóbano', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60112, 'Chacarita', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60113, 'Chira', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60114, 'Acapulco', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60115, 'El Roble', 601);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60116, 'Arancibia', 601);
-- Cantón 602
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60201, 'Espíritu Santo', 602);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60202, 'San Juan Grande', 602);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60203, 'Macacona', 602);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60204, 'San Rafael', 602);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60205, 'San Jerónimo', 602);
-- Cantón 603
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60301, 'Buenos Aires', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60302, 'Volcán', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60303, 'Potrero Grande', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60304, 'Boruca', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60305, 'Pilas', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60306, 'Colinas', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60307, 'Chánguena', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60308, 'Biolley', 603);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60309, 'Brunka', 603);
-- Cantón 604
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60401, 'Miramar', 604);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60402, 'La Unión', 604);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60403, 'San Isidro', 604);
-- Cantón 605
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60501, 'Puerto Cortés', 605);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60502, 'Palmar', 605);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60503, 'Sierpe', 605);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60504, 'Bahía Ballena', 605);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60505, 'Piedras Blancas', 605);
-- Cantón 606
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60601, 'Quepos', 606);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60602, 'Savegre', 606);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60603, 'Naranjito', 606);
-- Cantón 607
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60701, 'Golfito', 607);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60702, 'Puerto Jiménez', 607);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60703, 'Guaycará', 607);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60704, 'Pavón', 607);
-- Cantón 608
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60801, 'San Vito', 608);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60802, 'Sabalito', 608);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60803, 'Aguabuena', 608);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60804, 'Limoncito', 608);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60805, 'Pittier', 608);
-- Cantón 609
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (60901, 'Parrita', 609);
-- Cantón 610
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (61001, 'Corredor', 610);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (61002, 'La Cuesta', 610);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (61003, 'Canoas', 610);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (61004, 'Laurel', 610);
-- Cantón 611
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (61101, 'Jacó', 611);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (61102, 'Tárcoles', 611);

--DISTRITOS DE LIMON

-- Cantón 701
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70101, 'Limón', 701);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70102, 'Valle La Estrella', 701);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70103, 'Río Blanco', 701);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70104, 'Matama', 701);
-- Cantón 702
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70201, 'Guápiles', 702);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70202, 'Jiménez', 702);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70203, 'La Rita', 702);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70204, 'Roxana', 702);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70205, 'Cariari', 702);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70206, 'Colorado', 702);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70207, 'La Colonia', 702);
-- Cantón 703
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70301, 'Siquirres', 703);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70302, 'Pacuarito', 703);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70303, 'Florida', 703);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70304, 'Germania', 703);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70305, 'El Cairo', 703);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70306, 'Alegría', 703);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70307, 'Reventazón', 703);
-- Cantón 704
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70401, 'Bratsi', 704);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70402, 'Sixaola', 704);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70403, 'Cahuita', 704);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70404, 'Telire', 704);
-- Cantón 705
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70501, 'Matina', 705);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70502, 'Batán', 705);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70503, 'Carrandi', 705);
-- Cantón 706
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70601, 'Guácimo', 706);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70602, 'Mercedes', 706);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70603, 'Pocora', 706);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70604, 'Río Jiménez', 706);
INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_CANTON) VALUES (70605, 'Duacarí', 706);

COMMIT;

--INSERT DE TIENDAS
-- San José
INSERT INTO FIDE_ARATIENDA.FIDE_DIRECCION_TB (ID_PROVINCIA, ID_CANTON, ID_DISTRITO, DESCRIPCION)
VALUES (1, 101, 10101, 'Centro de San José');

INSERT INTO FIDE_ARATIENDA.FIDE_TIENDAS_TB (NOMBRE_TIENDA, ID_DIRECCION)
VALUES ('Tienda San José', FIDE_DIRECCION_SEQ.CURRVAL);

-- Guanacaste
INSERT INTO FIDE_ARATIENDA.FIDE_DIRECCION_TB (ID_PROVINCIA, ID_CANTON, ID_DISTRITO, DESCRIPCION)
VALUES (5, 501, 50101, 'Centro de Liberia');

INSERT INTO FIDE_ARATIENDA.FIDE_TIENDAS_TB (NOMBRE_TIENDA, ID_DIRECCION)
VALUES ('Tienda Guanacaste', FIDE_DIRECCION_SEQ.CURRVAL);

-- Puntarenas
INSERT INTO FIDE_ARATIENDA.FIDE_DIRECCION_TB (ID_PROVINCIA, ID_CANTON, ID_DISTRITO, DESCRIPCION)
VALUES (6, 601, 60101, 'Centro de Puntarenas');

INSERT INTO FIDE_ARATIENDA.FIDE_TIENDAS_TB (NOMBRE_TIENDA, ID_DIRECCION)
VALUES ('Tienda Puntarenas', FIDE_DIRECCION_SEQ.CURRVAL);

-- Limón
INSERT INTO FIDE_ARATIENDA.FIDE_DIRECCION_TB (ID_PROVINCIA, ID_CANTON, ID_DISTRITO, DESCRIPCION)
VALUES (7, 701, 70101, 'Centro de Limón');

INSERT INTO FIDE_ARATIENDA.FIDE_TIENDAS_TB (NOMBRE_TIENDA, ID_DIRECCION)
VALUES ('Tienda Limón', FIDE_DIRECCION_SEQ.CURRVAL);

-- Cartago
INSERT INTO FIDE_ARATIENDA.FIDE_DIRECCION_TB (ID_PROVINCIA, ID_CANTON, ID_DISTRITO, DESCRIPCION)
VALUES (2, 201, 20101, 'Centro de Cartago');

INSERT INTO FIDE_ARATIENDA.FIDE_TIENDAS_TB (NOMBRE_TIENDA, ID_DIRECCION)
VALUES ('Tienda Cartago', FIDE_DIRECCION_SEQ.CURRVAL);
COMMIT;