-- 1. Usuarios
CREATE SEQUENCE FIDE_USUARIOS_SEQ START WITH 1000 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_USERS_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_USUARIOS_TB
FOR EACH ROW
WHEN (NEW.ID_USUARIO IS NULL)
BEGIN
    SELECT FIDE_USUARIOS_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END;
/

-- 2. Direcciones
CREATE SEQUENCE FIDE_DIRECCION_SEQ START WITH 12 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_DIRECCION_TB
FOR EACH ROW
WHEN (NEW.ID_DIRECCION IS NULL)
BEGIN
    SELECT FIDE_DIRECCION_SEQ.NEXTVAL INTO :NEW.ID_DIRECCION FROM DUAL;
END;
/

-- 3. Estados
CREATE SEQUENCE FIDE_ESTADOS_SEQ START WITH 1 INCREMENT BY 1;

-- 4. Moneda
CREATE SEQUENCE FIDE_MONEDA_SEQ START WITH 1 INCREMENT BY 1;

-- 5. Forma de pago
CREATE SEQUENCE FIDE_FORMA_PAGO_SEQ START WITH 1 INCREMENT BY 1;

-- 6. Clientes
CREATE SEQUENCE FIDE_CLIENTES_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_CLIENTES_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_CLIENTES_TB
FOR EACH ROW
WHEN (NEW.ID_CLIENTE IS NULL)
BEGIN
    SELECT FIDE_CLIENTES_SEQ.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
END;
/

-- 7. Empleados
CREATE SEQUENCE FIDE_EMPLEADOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_EMPLEADOS_TB
FOR EACH ROW
WHEN (NEW.ID_EMPLEADO IS NULL)
BEGIN
    SELECT FIDE_EMPLEADOS_SEQ.NEXTVAL INTO :NEW.ID_EMPLEADO FROM DUAL;
END;
/

-- 8. Productos
CREATE SEQUENCE FIDE_PRODUCTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_PRODUCTOS_TB
FOR EACH ROW
WHEN (NEW.ID_PRODUCTO IS NULL)
BEGIN
    SELECT FIDE_PRODUCTOS_SEQ.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL;
END;
/

-- 9. Inventario
CREATE SEQUENCE FIDE_INVENTARIO_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_INVENTARIO_TB
FOR EACH ROW
WHEN (NEW.ID_INVENTARIO IS NULL)
BEGIN
    SELECT FIDE_INVENTARIO_SEQ.NEXTVAL INTO :NEW.ID_INVENTARIO FROM DUAL;
END;
/

-- 10. Tiendas
CREATE SEQUENCE FIDE_TIENDAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_TIENDAS_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_TIENDAS_TB
FOR EACH ROW
WHEN (NEW.ID_TIENDA IS NULL)
BEGIN
    SELECT FIDE_TIENDAS_SEQ.NEXTVAL INTO :NEW.ID_TIENDA FROM DUAL;
END;
/

-- 11. Cajas
CREATE SEQUENCE FIDE_CAJAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_CAJAS_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_CAJAS_TB
FOR EACH ROW
WHEN (NEW.ID_CAJA IS NULL)
BEGIN
    SELECT FIDE_CAJAS_SEQ.NEXTVAL INTO :NEW.ID_CAJA FROM DUAL;
END;
/

-- 12. Facturas
CREATE SEQUENCE FIDE_FACTURAS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_FACTURAS_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_FACTURAS_TB
FOR EACH ROW
WHEN (NEW.ID_FACTURA IS NULL)
BEGIN
    SELECT FIDE_FACTURAS_SEQ.NEXTVAL INTO :NEW.ID_FACTURA FROM DUAL;
END;
/

-- 13. Detalle de factura
CREATE SEQUENCE FIDE_DETALLE_FACTURA_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
WHEN (NEW.ID_DETALLE IS NULL)
BEGIN
    SELECT FIDE_DETALLE_FACTURA_SEQ.NEXTVAL INTO :NEW.ID_DETALLE FROM DUAL;
END;
/

-- 14. Notas de crédito
CREATE SEQUENCE FIDE_NOTAS_CREDITO_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER FIDE_NOTAS_CREDITO_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_NOTAS_CREDITO_TB
FOR EACH ROW
WHEN (NEW.ID_NOTA_CREDITO IS NULL)
BEGIN
    SELECT FIDE_NOTAS_CREDITO_SEQ.NEXTVAL INTO :NEW.ID_NOTA_CREDITO FROM DUAL;
END;
/

--FIDE_PRODUCTO_TIENDA_TB
CREATE SEQUENCE FIDE_PRODUCTO_TIENDA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_TIENDA_TB_ID_TRG
BEFORE INSERT ON FIDE_ARATIENDA.FIDE_PRODUCTO_TIENDA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROD_TIENDA IS NULL THEN
        SELECT FIDE_PRODUCTO_TIENDA_SEQ.NEXTVAL
        INTO :NEW.ID_PROD_TIENDA
        FROM DUAL;
    END IF;
END;
/



