
CREATE USER FIDE_ARATIENDA IDENTIFIED BY ARATIENDA;
GRANT CONNECT TO FIDE_ARATIENDA;
GRANT RESOURCE TO FIDE_ARATIENDA;
GRANT DBA TO FIDE_ARATIENDA;
GRANT CREATE SESSION TO FIDE_ARATIENDA;


-- 1. Tabla de roles
CREATE TABLE FIDE_ARATIENDA.FIDE_ROLES_TB (
    ID_ROL      NUMBER PRIMARY KEY,
    NOMBRE_ROL  VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255)
);

-- 2. Tabla de usuarios
CREATE TABLE FIDE_ARATIENDA.FIDE_USUARIOS_TB (
    ID_USUARIO       NUMBER PRIMARY KEY,
    NOMBRE           VARCHAR2(100) NOT NULL,
    APELLIDO1        VARCHAR2(100),
    APELLIDO2        VARCHAR2(100),
    CORREO           VARCHAR2(255) UNIQUE NOT NULL,
    TELEFONO         VARCHAR2(20),
    FECHA_NACIMIENTO DATE,
    CONTRASENA       VARCHAR2(255) NOT NULL,
    ID_ROL           NUMBER NOT NULL,
    ESTADO           NUMBER DEFAULT 1,
    CREADO_POR       VARCHAR2(100),
    CREADO_EL        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFICADO_POR   VARCHAR2(100),
    MODIFICADO_EL    TIMESTAMP,
    CONSTRAINT FIDE_USUARIOS_FK_ROL FOREIGN KEY (ID_ROL)
        REFERENCES FIDE_ARATIENDA.FIDE_ROLES_TB(ID_ROL)
);

-- 3. Tabla de país
CREATE TABLE FIDE_ARATIENDA.FIDE_PAIS_TB (
    ID_PAIS INT PRIMARY KEY,
    NOMBRE_PAIS VARCHAR2(100) NOT NULL
);

-- 4. Tabla de provincia
CREATE TABLE FIDE_ARATIENDA.FIDE_PROVINCIA_TB (
    ID_PROVINCIA NUMBER PRIMARY KEY,
    NOMBRE_PROVINCIA VARCHAR2(100) NOT NULL
);

-- 5. Tabla de cantón
CREATE TABLE FIDE_ARATIENDA.FIDE_CANTON_TB (
    ID_CANTON NUMBER PRIMARY KEY,
    NOMBRE_CANTON VARCHAR2(100) NOT NULL,
    ID_PROVINCIA NUMBER NOT NULL,
    CONSTRAINT FK_CANTON_PROVINCIA FOREIGN KEY (ID_PROVINCIA)
        REFERENCES FIDE_ARATIENDA.FIDE_PROVINCIA_TB(ID_PROVINCIA)
);

-- 6. Tabla de distrito
CREATE TABLE FIDE_ARATIENDA.FIDE_DISTRITO_TB (
    ID_DISTRITO NUMBER PRIMARY KEY,
    NOMBRE_DISTRITO VARCHAR2(100) NOT NULL,
    ID_CANTON NUMBER NOT NULL,
    CONSTRAINT FK_DISTRITO_CANTON FOREIGN KEY (ID_CANTON)
        REFERENCES FIDE_ARATIENDA.FIDE_CANTON_TB(ID_CANTON)
);

-- 7. Tabla de direcciones
CREATE TABLE FIDE_ARATIENDA.FIDE_DIRECCION_TB (
    ID_DIRECCION INT PRIMARY KEY,
    ID_PROVINCIA INT NOT NULL,
    ID_CANTON INT NOT NULL,
    ID_DISTRITO INT NOT NULL,
    ID_PAIS INT DEFAULT 506,
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT FK_DIRECCION_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES FIDE_ARATIENDA.FIDE_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FK_DIRECCION_CANTON FOREIGN KEY (ID_CANTON) REFERENCES FIDE_ARATIENDA.FIDE_CANTON_TB(ID_CANTON),
    CONSTRAINT FK_DIRECCION_DISTRITO FOREIGN KEY (ID_DISTRITO) REFERENCES FIDE_ARATIENDA.FIDE_DISTRITO_TB(ID_DISTRITO),
    CONSTRAINT FK_DIRECCION_PAIS FOREIGN KEY (ID_PAIS) REFERENCES FIDE_ARATIENDA.FIDE_PAIS_TB(ID_PAIS)
);

-- 8. Tabla de estados
CREATE TABLE FIDE_ARATIENDA.FIDE_ESTADOS_TB (
    ID_ESTADO NUMBER PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(100) NOT NULL
);

-- 9. Tabla de moneda
CREATE TABLE FIDE_ARATIENDA.FIDE_MONEDA_TB (
    ID_MONEDA NUMBER PRIMARY KEY,
    NOMBRE_MONEDA VARCHAR2(50) NOT NULL
);

-- 10. Tabla de forma de pago
CREATE TABLE FIDE_ARATIENDA.FIDE_FORMA_PAGO_TB (
    ID_FORMA_PAGO NUMBER PRIMARY KEY,
    NOMBRE_FORMA_PAGO VARCHAR2(100) NOT NULL
);

-- 11. Tabla de clientes
CREATE TABLE FIDE_ARATIENDA.FIDE_CLIENTES_TB (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR2(100) NOT NULL,
    APELLIDO_CLIENTE VARCHAR2(100),
    CORREO VARCHAR2(255),
    TELEFONO VARCHAR2(20),
    ID_DIRECCION NUMBER
);

-- 12. Tabla de empleados
CREATE TABLE FIDE_ARATIENDA.FIDE_EMPLEADOS_TB (
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100),
    CORREO VARCHAR2(255),
    TELEFONO VARCHAR2(20),
    ID_DIRECCION NUMBER
);

-- 13. Tabla de productos
CREATE TABLE FIDE_ARATIENDA.FIDE_PRODUCTOS_TB (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR2(100),
    PRECIO DECIMAL(10,2)
);

-- 14. Tabla de inventario
CREATE TABLE FIDE_ARATIENDA.FIDE_INVENTARIO_TB (
    ID_INVENTARIO NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD_DISPONIBLE NUMBER NOT NULL,
    CONSTRAINT FK_INVENTARIO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_ARATIENDA.FIDE_PRODUCTOS_TB(ID_PRODUCTO)
);

-- 15. Tabla de tiendas
CREATE TABLE FIDE_ARATIENDA.FIDE_TIENDAS_TB (
    ID_TIENDA NUMBER PRIMARY KEY,
    NOMBRE_TIENDA VARCHAR2(100),
    ID_DIRECCION NUMBER
);

-- 16. Tabla de relación producto-tienda (inventario distribuido)
CREATE TABLE FIDE_ARATIENDA.FIDE_PRODUCTO_TIENDA_TB (
    ID_PROD_TIENDA NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER NOT NULL,
    ID_TIENDA NUMBER NOT NULL,
    CANTIDAD_DISPONIBLE NUMBER NOT NULL,
    CONSTRAINT FK_PROD_TIENDA_PRODUCTO FOREIGN KEY (ID_PRODUCTO)
        REFERENCES FIDE_ARATIENDA.FIDE_PRODUCTOS_TB(ID_PRODUCTO),
    CONSTRAINT FK_PROD_TIENDA_TIENDA FOREIGN KEY (ID_TIENDA)
        REFERENCES FIDE_ARATIENDA.FIDE_TIENDAS_TB(ID_TIENDA)
);

-- 17. Tabla de cajas
CREATE TABLE FIDE_ARATIENDA.FIDE_CAJAS_TB (
    ID_CAJA NUMBER PRIMARY KEY,
    ID_TIENDA NUMBER NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    NOMBRE_CAJA VARCHAR2(100),
    CONSTRAINT FK_CAJA_TIENDA FOREIGN KEY (ID_TIENDA) REFERENCES FIDE_ARATIENDA.FIDE_TIENDAS_TB(ID_TIENDA),
    CONSTRAINT FK_CAJA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_ARATIENDA.FIDE_EMPLEADOS_TB(ID_EMPLEADO)
);

-- 18. Tabla de facturas
CREATE TABLE FIDE_ARATIENDA.FIDE_FACTURAS_TB (
    ID_FACTURA NUMBER PRIMARY KEY,
    ID_MONEDA NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    ID_FORMA_PAGO NUMBER NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    ID_NOTA_CREDITO NUMBER,
    SUBTOTAL DECIMAL(10,2),
    TOTAL DECIMAL(10,2),
    FECHA DATE DEFAULT SYSDATE,
    CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES FIDE_ARATIENDA.FIDE_CLIENTES_TB(ID_CLIENTE),
    CONSTRAINT FK_FACTURA_PAGO FOREIGN KEY (ID_FORMA_PAGO) REFERENCES FIDE_ARATIENDA.FIDE_FORMA_PAGO_TB(ID_FORMA_PAGO),
    CONSTRAINT FK_FACTURA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES FIDE_ARATIENDA.FIDE_EMPLEADOS_TB(ID_EMPLEADO),
    CONSTRAINT FK_FACTURA_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES FIDE_ARATIENDA.FIDE_MONEDA_TB(ID_MONEDA),
    CONSTRAINT FK_FACTURA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ARATIENDA.FIDE_ESTADOS_TB(ID_ESTADO)
);

-- 19. Tabla de detalle de factura
CREATE TABLE FIDE_ARATIENDA.FIDE_DETALLE_FACTURA_TB (
    ID_DETALLE NUMBER PRIMARY KEY,
    ID_FACTURA NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2),
    CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FIDE_ARATIENDA.FIDE_FACTURAS_TB(ID_FACTURA)
);

-- 20. Tabla de notas de crédito
CREATE TABLE FIDE_ARATIENDA.FIDE_NOTAS_CREDITO_TB (
    ID_NOTA_CREDITO NUMBER PRIMARY KEY,
    ID_FACTURA NUMBER NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA DATE DEFAULT SYSDATE,
    MOTIVO VARCHAR2(255),
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FK_NOTA_CREDITO_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FIDE_ARATIENDA.FIDE_FACTURAS_TB(ID_FACTURA),
    CONSTRAINT FK_NOTA_CREDITO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ARATIENDA.FIDE_ESTADOS_TB(ID_ESTADO)
);



























